### ISSUE TITLE
Fastlane fixes

### ISSUE THREAD

**Issue by IzzySoft** [the-weird-aquarian/OpenRec#3]
You've got 2 minor issues with your Fastlane structure:

* in `de-DE`, the file `description.txt` must be renamed to `full_description.txt`
* if you could add an empty line before the unordered list, it would be recognizable as such (currently, it would form a full paragraph together with the line preceding it)

Thanks for checking!

**Comment by StellarSand** [comment]
Nice catch. The said fixes has been applied. Kindly check and let me know :)

**Comment by IzzySoft** [comment]
Confirmed, thanks! Updated the config on my end so full description will be fetched as well now when there are new releases. You might wish to place the screenshots (from your Readme) into `en-US/images/phoneScreenshots/`, and they could join the party as well :smiley: Let me know if you did so, so I adjust the config at my end accordingly.

Uh, in case I forgot to give the background: Your app is [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.openrec) and thus can be found, installed and be kept updated using the [F-Droid](https://f-droid.org/) client. If you wish, you can use [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there, eg. from your Readme.
